### ISSUE TITLE
A1111 Extension gets: 500 Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by Davey212** [antfu/sd-webui-qrcode-toolkit#2]
### Describe the bug

In version ce75e181 of extension, Message occurs in Edge and Chrome with all extensions disabled and tracking prevention turned off

### Reproduction

Edge and Chrome browsers

### System Info

```Shell
A1111: version: v1.4.0  •  python: 3.10.10  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: 77b7dc4ef0  

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
    Memory: 7.68 GB / 15.91 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)

In version ce75e181 of extension, Message occurs in Edge with all extensions disabled and tracking prevention turned off, also happens in Chrome. Extension works in Vivaldi, Brave and FireFox.

This extension does not run completely local?
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ene0s** [comment]
According to chromium ressources it seems this issue is when 3rd parties cookies can't be written
(https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document)

Seems it is calling this web app and not running locally : https://qrcode.antfu.me/. Set up an exception in the 'cookies from 3rd parties' in you web browser preferences to allow this domain and the extension will work. Thus said, I'd also prefer for it to run locally.

**Comment by Davey212** [comment]
Allowing 3rd party cookies fixed issue.
